name: bottom_rs_dart
description: Dart bindings for bottom-rs-lib
version: 0.0.1
homepage: "https://timko.one"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  test: "1.15.7"
  system_info: ^0.1.3
  ffi: ^0.1.3
