[package]
name = "bottom_rs_lib_ffi"
version = "1.0.0"
edition = "2018"

[lib]
name = "bottom_rs_lib_ffi"
crate-type = ["cdylib", "staticlib", "dylib"]

[dependencies]
bottom-rs-lib = { path = "../bottom-rs-lib" }
libc = "0.2.86"